### ISSUE TITLE
Add video recording using GStreamer

### ISSUE THREAD

**Issue by cfobel** [wheeler-microfluidics/microdrop#113]

**Comment by cfobel** [comment]
Trac update at 20120801T15:57:12: ryan changed milestone from "0.3" to "0.2"

**Comment by cfobel** [comment]
Trac update at 20120801T15:58:43: ryan changed status from "new" to "assigned"

**Comment by cfobel** [comment]
Trac update at 20140312T20:02:01: ryan changed milestone from "1.0" to "1.1"

**Comment by cfobel** [comment]
Trac update at 20140313T20:00:48: ryan changed milestone from "1.1" to ""

**Comment by ryanfobel** [comment]
The GTK device view is going to be deprecated in favor of the [webui-plugin](https://github.com/wheeler-microfluidics/webui-plugin).
