### ISSUE TITLE
Add support for `on_plugin_install.py` file in plugins (Trac #155)

### ISSUE THREAD

**Issue by cfobel** [wheeler-microfluidics/microdrop#159]
* Add support for `on_plugin_install.py` file in plugins.
* Upon installation of plugin, execute the `on_plugin_install.py` script using the same Python executable used to run MicroDrop.
* The `on_plugin_install.py` can, *e.g.*, be used to install dependencies using `pip`.

**Comment by ryanfobel** [comment]
This feature was added a long time ago...
