### ISSUE TITLE
Improvements to build/package/testing infrastructure

### ISSUE THREAD

**Issue by cfobel** [wheeler-microfluidics/microdrop#201]
For [MicroDrop v2.0][v2.0], we moved to a [Miniconda](http://conda.pydata.org/miniconda.html)-based installer.

There's a lot of work to do in creating conda packages for all of our projects, making these packages cross-platform, and setting up automated build and testing triggered by git hooks.

See also [development roadmap][1].

**Legend** - **[x]**: Done, **[i]**: In progress, **[ ]**: To do

 - **[i]** Bundle MicroDrop and dependencies as [Conda][conda] packages
     * **[x]** Windows 32-bit
     * **[i]** Linux 32-bit
 - **[ ]** Configure [AppVeyor][appveyor]:
     * **[ ]** Build Windows Conda packages.
     * **[ ]** Test Windows Conda packages.
 - **[ ]** Configure [Travis CI][travis-ci]:
     * **[ ]** Build Linux Conda packages.
     * **[ ]** Test Linux Conda packages.

[1]: https://github.com/wheeler-microfluidics/microdrop/wiki/MicroDrop-RoadMap
[v2.0]: https://github.com/wheeler-microfluidics/microdrop/wiki/MicroDrop-v2.0-SoftwareArchitecture
[travis-ci]: https://travis-ci.org/
[appveyor]: https://www.appveyor.com/
[conda]: http://conda.pydata.org/docs/

**Comment by ryanfobel** [comment]
This issues has been broken into several sub-components.
