### ISSUE TITLE
Transition user interface to the browser

### ISSUE THREAD

**Issue by cfobel** [wheeler-microfluidics/microdrop#202]
We'd like to rewrite MicroDrop's user interface using a [Jupyter Lab](http://jupyterlab.github.io/jupyterlab/)/[PhosphorJS][phosphor.js] browser-based layout (e.g., existing [webui-plugin](https://github.com/wheeler-microfluidics/webui-plugin)). This will make it easier to install/maintain a version of MicroDrop that can easily run on different platforms including phones and tablets.

The plan is to have each component of the UI be packaged independently as a [PhosphorJS][phosphor.js] widget.  Each [PhosphorJS][phosphor.js] widget is a simple class that corresponds to a `<div>` tag in the browser window, which can be filled with arbitrary HTML (e.g., existing [webui-plugin][webui-plugin]).

**Legend** - **[x]**: Done, **[i]**: In progress, **[ ]**: To do

 - **[ ]** Switch to non-GUI main run loop (e.g., [Tornado IOLoop][ioloop]) #218
 - **[ ]** Migrate all UI (i.e., GTK 2.0) code to non-core plugins #217
 - **[i]** Develop web-browser based MicroDrop UI (see [here][webui-plugin])

[webui-plugin]: https://github.com/wheeler-microfluidics/webui-plugin
[ioloop]: http://pyzmq.readthedocs.io/en/latest/eventloop.html
[phosphor.js]: http://phosphorjs.github.io/

**Comment by ryanfobel** [comment]
Split into sub-components #217 and #218
