### ISSUE TITLE
New language agnostic, network compatible plugin framework

### ISSUE THREAD

**Issue by cfobel** [wheeler-microfluidics/microdrop#203]
**See also:**
 - [ZeroMQ plugin framework]
 - [MicroDrop Roadmap](https://github.com/wheeler-microfluidics/microdrop/wiki/Development-roadmap)

---------------------------------------------------------------

We are planning to transition to a new plugin framework using a [hub and spoke][hub-spoke] architecture (our current implementation is based on [zeromq](http://zeromq.org/) messaging). The goal is allow each plugin to operate as an independent process that registers with a [central hub](https://github.com/wheeler-microfluidics/zmq-plugin). Other goals of this framework are:

1. To be language agnostic (i.e., support plugins written in any language)
2. To allow plugins to run on a single computer or multiple computers connected over a network
3. Others?

Plugins can publish and subscribe to messages exposed through the hub. Some of this functionality is already implemented in MicroDrop 2.0 (e.g., the [central hub](https://github.com/wheeler-microfluidics/zmq-plugin), [dmf_device_ui_plugin](https://github.com/wheeler-microfluidics/dmf_device_ui_plugin)) but the intention is to migrate all existing plugins to using this framework and drop the PyUtilib-based system.

Some outstanding issues related to this process:

**Legend** - **[x]**: Done, **[i]**: In progress, **[ ]**: To do

 - **[i]** **Language agnostic**, **network compatible** plugin
   **communication**
     * **[x]** Add [`zmq_hub_plugin`][md-zmq-hub] as a core MicroDrop plugin
     * **[i]** Port existing **[PyUtilib Component Architecture][pca]-based plugins to use the [ZeroMQ plugin framework] API.
 - **[ ]** New hook for launching v2.0 plugins: #197
 - **[ ]** Add support to specify plugin requirements as Conda packages (i.e., `conda-requirements.txt`) #199

[hub-spoke]: http://www.enterpriseintegrationpatterns.com/ramblings/03_hubandspoke.html
[zmq-plugin]: https://github.com/wheeler-microfluidics/zmq-plugin
[md-zmq-hub]: https://github.com/wheeler-microfluidics/microdrop/blob/19d4393a26a556ed79b902c12d98c50d23578c5c/microdrop/core_plugins/zmq_hub_plugin/__init__.py#L76-L97
[pca]: https://software.sandia.gov/trac/pyutilib/export/1831/pyutilib.component.doc/trunk/doc/plugin/pca.pdf
[ZeroMQ plugin framework]: https://github.com/wheeler-microfluidics/microdrop/wiki/ZeroMQ-plugin-framework

**Comment by ryanfobel** [comment]
This issue has been split into several sub-components: #197, #199, and #207.
