### ISSUE TITLE
Add ability to plot current, force and actuation voltage (Trac #49)

### ISSUE THREAD

**Issue by cfobel** [wheeler-microfluidics/microdrop#53]
Migrated from http://microfluidics.utoronto.ca/ticket/49

``` json
{
    "status": "new", 
    "changetime": "2014-04-17T19:40:13", 
    "description": "\n", 
    "reporter": "ryan", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1397763613851119", 
    "component": "microdrop", 
    "summary": "Add ability to plot current, force and actuation voltage", 
    "priority": "minor", 
    "keywords": "", 
    "version": "0.1", 
    "time": "2012-02-20T03:47:13", 
    "milestone": "Microdrop 1.1", 
    "owner": "ryan", 
    "type": "enhancement"
}
```

**Comment by cfobel** [comment]
Trac update at 20120220T04:04:55: ryan changed summary from "Add ability to plog current, force and actuation voltage" to "Add ability to plot current, force and actuation voltage"

**Comment by cfobel** [comment]
Trac update at 20120801T15:49:39: ryan changed milestone from "0.2" to "0.3"

**Comment by cfobel** [comment]
Trac update at 20140417T19:40:13: ryan changed component from "gui" to "microdrop"

**Comment by ryanfobel** [comment]
This was implemented a long time ago in the [dmf-control-board-plugin](https://github.com/wheeler-microfluidics/dmf_control_board_plugin).
