### ISSUE TITLE
Add option to display feedback threshold on graphs (Trac #52)

### ISSUE THREAD

**Issue by cfobel** [wheeler-microfluidics/microdrop#56]

**Comment by cfobel** [comment]
Trac update at 20140312T20:02:01: ryan changed milestone from "1.0" to "1.1"

**Comment by cfobel** [comment]
Trac update at 20140313T20:00:48: ryan changed milestone from "1.1" to ""

**Comment by ryanfobel** [comment]
Migrated this issue to the [DMF control board plugin issue tracker](https://github.com/wheeler-microfluidics/dmf_control_board_plugin/issues/3).
