### ISSUE TITLE
Add tool for cycling through electrodes on device

### ISSUE THREAD

**Issue by cfobel** [wheeler-microfluidics/microdrop#57]
This could be used to check that all electrodes are connected (i.e., measure capacitance of air gap) and/or to figure out on startup which reservoirs contain liquid.

**Comment by cfobel** [comment]
Trac update at 20120223T04:56:38: ryan changed description from "This could be used to check that are all electrodes are connected (i.e., measure capacitance of air gap) and/or to figure out on startup which reservoirs contain liquid." to "This could be used to check that all electrodes are connected (i.e., measure capacitance of air gap) and/or to figure out on startup which reservoirs contain liquid."

**Comment by cfobel** [comment]
Trac update at 20120302T02:02:49: ryan changed status from "new" to "accepted"

**Comment by cfobel** [comment]
Trac update at 20140312T20:02:01: ryan changed milestone from "1.0" to "1.1"

**Comment by cfobel** [comment]
Trac update at 20140417T19:40:13: ryan changed component from "core" to "microdrop"

**Comment by ryanfobel** [comment]
Migrated to https://github.com/wheeler-microfluidics/dmf_control_board_plugin/issues/5
