### ISSUE TITLE
Calibration wizard to measure feedback resistance/capacitance

### ISSUE THREAD

**Issue by cfobel** [wheeler-microfluidics/microdrop#58]
The control board has a bank of resistors used to measure device impedance and amplifier voltage. These resistors need to be characterized in order to get accurate measurements.

In addition, each resistor has an associated parasitic capacitance due to the cables, PCB traces, etc., which also need to be accounted for.

We should define a test load(s) that can be attached to the control board and have a wizard that will walk a user through a series of steps, collect the necessary data, fit curves and assign values to the calibration variables.

**Comment by cfobel** [comment]
Trac update at 20120310T16:05:25: ryan changed status from "new" to "accepted"

**Comment by cfobel** [comment]
Trac update at 20140312T20:02:01: ryan changed milestone from "1.0" to "1.1"

**Comment by cfobel** [comment]
Trac update at 20140417T19:40:13: ryan changed component from "core" to "microdrop"

**Comment by ryanfobel** [comment]
This was implemented a long time ago...
